# Site settings
title: Josh Hou &middot; 侯守仁
description: > # this means to ignore newlines until "baseurl:"
url: "https://joshuahou.com" # the base hostname & protocol for your site
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 2
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
